// libs/angular-ds/src/lib/components/base/text/text.component.ts
// Packages & Modules
import { toSnakeCase } from '@agensea-design-systems/utils';
import {
  Component,
  Input,
  OnChanges,
  OnInit,
  signal,
  SimpleChanges,
  WritableSignal
} from '@angular/core';
import { CommonModule } from '@angular/common';

// Definitions
import type { TTextProps } from './text.definitions';

// Component
@Component({
  selector: 'text-comp',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './text.component.html',
  styleUrl: './text.component.scss',
})
export class TextComp implements OnInit, OnChanges {
  // #region - INPUTS
  @Input() public casing: TTextProps['casing'] = 'unset';
  @Input() public className: TTextProps['className'];
  @Input() public decoration: TTextProps['decoration'] = 'none';
  @Input() public renderAs: TTextProps['renderAs'];
  @Input() public style: TTextProps['style'] = 'unset';
  @Input() public variant: TTextProps['variant'] = 'body md';
  @Input() public weight: TTextProps['weight'];
  // #endregion

  // #region - VARIABLES
  /**
   * Sets the base class name of the component.
   */
  public baseClass: string = 'text';
  // #endregion

  // #region - SIGNALS
  private _fontWeight: WritableSignal<TTextProps['weight']> = signal('regular');
  // #endregion
  
  // #region - METHODS
  /**
   * Sets the appropriate font weight based on the 'variant' prop.
   * 
   * @returns { void } - Returns nothing.
   */
  private setFontWeight(): void {
    switch (true) {
      case (
        !!this.weight &&
        typeof this.weight === 'string'
      ):
        this._fontWeight.set(this.weight);
        break;
      case this.variant === 'heading lg':
        this._fontWeight.set('extra bold');
        break;
      case (
        this.variant === 'heading md' ||
        this.variant === 'heading sm' ||
        this.variant === 'quote'
      ):
        this._fontWeight.set('bold');
        break;
      case (
        this.variant === 'sub-heading lg' ||
        this.variant === 'sub-heading md'
      ):
        this._fontWeight.set('semi bold');
        break;
      case this.variant === 'sub-heading sm':
        this._fontWeight.set('medium');
        break;
      default:
        this._fontWeight.set('regular');
        break;
    };
  }
  /**
   * Generates a list of class names to be added to the component
   * 
   * @returns { string } - The css class names to render on the component.
   */
  public getClassNames(): string {
    return (`
      ${ this.baseClass }
      ${ this.baseClass }--casing-${ toSnakeCase(this.casing || 'unset') }
      ${ this.baseClass }--decoration-${ toSnakeCase(this.decoration || 'none') }
      ${ this.baseClass }--style-${ toSnakeCase(this.style || '') }
      ${ this.baseClass }--variant-${ toSnakeCase(this.variant ||'body md') }
      ${ this.baseClass }--weight-${ toSnakeCase(this._fontWeight() || 'regular') }
      ${ this.className ? this.className : '' }
    `);
  }
  // #endregion

  // #region - LIFECYCLE METHODS
  public ngOnInit(): void {
    this.setFontWeight();
  }

  public ngOnChanges(changes: SimpleChanges): void {
    if (changes['weight'] || changes['variant']) {
      this.setFontWeight();
    }
  }
  // #endregion
}

<!-- HTML Tag -->
@switch (true) {
  @case (
    renderAs &&
    renderAs === 'label'
  ) {
    <label [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </label>
  }
  @case (
    renderAs &&
    renderAs === 'span'
  ) {
    <span [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </span>
  }
  @case (
    this.renderAs &&
    this.renderAs === 'caption'
  ) {
    <caption [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </caption>
  }
  @case (this.variant === 'quote') {
    <blockquote [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </blockquote>
  }
  @case (this.variant === 'heading lg') {
    <h1 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h1>
  }
  @case (this.variant === 'heading md') {
    <h2 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h2>
  }
  @case (this.variant === 'heading sm') {
    <h3 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h3>
  }
  @case (this.variant === 'sub-heading lg') {
    <h4 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h4>
  }
  @case (this.variant === 'sub-heading md') {
    <h5 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h5>
  }
  @case (
    this.variant === 'sub-heading sm' ||
    this.variant === 'tagline'
  ) {
    <h6 [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </h6>
  }
  @default {
    <p [class]="getClassNames()">
      <ng-container [ngTemplateOutlet]="content" />
    </p>
  }
}
<!-- HTML Tag -->

<!-- Content -->
<ng-template #content>
  <ng-content />
</ng-template>
<!-- ./Content -->

// libs/react-ds/src/lib/components/base/text/text.tsx
'use client'

// Packages & Modules
import { toSnakeCase } from '@agensea-design-systems/utils';
import styles from './text.module.scss';
import {
  useEffect,
  useState
} from 'react';

// Definitions
import type {
  TTextProps,
  TTextTag
} from './text.definitions';
import type { PropsWithChildren } from 'react';

// Component
export const Text = ( props: PropsWithChildren< TTextProps > ): JSX.Element => {
  // #region - PROPS
  const {
    casing = 'unset',
    children,
    className,
    decoration = 'none',
    renderAs,
    style = 'unset',
    variant = 'body md',
    weight
  } = props;
  // #endregion

  // #region - VARIABLES
  /**
   * Sets the base class name of the component.
   */
  const baseClass: string = 'text';
  // #endregion
  
  // #region - STATES
  /**
   * Stores the HTML tag element to render.
   */
  const [
    _tag,
    _setTag
  ] = useState<TTextTag>();
  /**
   * Stores the font weight value to render.
   */
  const [
    _fontWeight,
    _setFontWeight
  ] = useState<TTextProps['weight']>();
  // #endregion

  // #region - METHODS
  /**
   * Sets the appropriate HTML tag based on the 'renderAs' and 'variant' props.
   * 
   * @returns { void } - Returns nothing.
   */
  const setTag = (): void => {
    switch (true) {
      case (
        renderAs &&
        renderAs === 'label'
      ):
        _setTag('label');
        break;
      case (
        renderAs &&
        renderAs === 'span'
      ):
        _setTag('span');
        break;
      case (
        renderAs &&
        renderAs === 'caption'
      ):
        _setTag('caption');
        break;
      case variant === 'quote':
        _setTag('blockquote');
        break;
      case variant === 'heading lg':
        _setTag('h1');
        break;
      case variant === 'heading md':
        _setTag('h2');
        break;
      case variant === 'heading sm':
        _setTag('h3');
        break;
      case variant === 'sub-heading lg':
        _setTag('h4');
        break;
      case variant === 'sub-heading md':
        _setTag('h5');
        break;
      case (
        variant === 'sub-heading sm' ||
        variant === 'tagline'
      ):
        _setTag('h6');
        break;
      default:
        _setTag('p');
        break;
    };
  }
  /**
   * Sets the appropriate font weight based on the 'variant' prop.
   * 
   * @returns { void } - Returns nothing.
   */
  const setFontWeight = (): void => {
    switch (true) {
      case variant === 'heading lg':
        _setFontWeight('extra bold');
        break;
      case (
        variant === 'heading md' ||
        variant === 'heading sm' ||
        variant === 'quote'
      ):
        _setFontWeight('bold');
        break;
      case (
        variant === 'sub-heading lg' ||
        variant === 'sub-heading md'
      ):
        _setFontWeight('semi bold');
        break;
      case variant === 'sub-heading sm':
        _setFontWeight('medium');
        break;
      default:
        _setFontWeight('regular');
        break;
    };
  }
  // #endregion

  // #region - EFFECTS
  useEffect(() => {
    setTag();
  }, [
    renderAs,
    variant,
  ]);

  useEffect(() => {
    if (!weight) {
      setFontWeight();
    } else {
      _setFontWeight(weight);
    }
  }, [
    variant,
    weight
  ]);
  // #endregion

  // #region - HTML
  return (
    <>
      {(_tag) && (
        <_tag
          className={`
            ${ styles[baseClass] }
            ${ styles[`${ baseClass }--casing-${ toSnakeCase(casing) }`] }
            ${ styles[`${ baseClass }--decoration-${ toSnakeCase(decoration) }`] }
            ${ styles[`${ baseClass }--style-${ toSnakeCase(style) }`] }
            ${ styles[`${ baseClass }--variant-${ toSnakeCase(variant) }`] }
            ${ styles[`${ baseClass }--weight-${ toSnakeCase(_fontWeight || 'regular') }`] }
            ${ className ? className : '' }
          `}
        >
          { children }
        </_tag>
      )}
    </>
  );
  // #endregion
}
